// Order Details

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_SUCCESSID = "ORDER_DETAILS_SUCCESSID"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

export const CREATE_DETAILS_REQUEST = "CREATE_DETAILS_REQUEST"
export const CREATE_DETAILS_SUCCESS = "CREATE_DETAILS_SUCCESS"
export const CREATE_DETAILS_FAIL = "CREATE_DETAILS_FAIL"
export const CREATE_DETAILS_RESET = "CREATE_DETAILS_RESET"

export const ORDER_UPDATE_REQUEST = "ORDER_UPDATE_REQUEST"
export const ORDER_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS"
export const ORDER_UPDATE_FAIL = "ORDER_UPDATE_FAIL"
export const ORDER_UPDATE_RESET = "ORDER_UPDATE_RESET"

export const ORDER_ADMIN_REQUEST = "ORDER_ADMIN_REQUEST"
export const ORDER_ADMIN_SUCCESS = "ORDER_ADMIN_SUCCESS"
export const ORDER_ADMIN_FAIL = "ORDER_ADMIN_FAIL"
export const ORDER_ADMIN_RESET = "ORDER_ADMIN_RESET"

